language: node_js # 构建所需的语言环境
node_js:
  - "v12.18.3"  # 对应的版本
branches:
  only:
  - master    # 构建的分支
cache:
  directories:
    - node_modules # 缓存 node_modules 加快构建速度
before_script: ## 根据你所用的主题和自定义的不同，这里会有所不同
  - npm install -g hexo-cli # 在 CI 环境内安装 Hexo  
  - npm install # 在根目录安装站点需要的依赖 
script:
  - hexo clean # 清除缓存
  - hexo generate # generate static files
  - hexo deploy
# deploy: # 根据个人情况，这里会有所不同
#   provider: pages
#   skip_cleanup: true # 构建完成后不清除
#   token: $GH_TOKEN # 你刚刚设置的 token
#   keep_history: true # 保存历史
#   fqdn: blog.ne0ng.page # 自定义域名，使用 username.github.io 可删除
#   on:
#     branch: source # hexo 站点源文件所在的 branch
#   local_dir: public 
#   target_branch: master # 存放生成站点文件的 branch，使用 username.github.io 必须是 master
