# 指定构建环境是Node.js，当前版本是稳定版
language: node_js
node_js: stable

env:
 global:
   - URL_REPO: https://github.com/wayofway/annwayart-blog

# 设置钩子只检测master分支的push变动
branches:
  only:
    - master

# 设置缓存文件
cache:
  directories:
    - node_modules

#在构建之前安装hexo环境
before_install:
  - npm install -g hexo-cli

#安装git插件和搜索功能插件
install:
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  # - hexo deploy

deploy: # 根据个人情况，这里会有所不同
  provider: pages
  skip_cleanup: true # 构建完成后不清除
  token: $GH_TOKEN # 你刚刚设置的 token
  keep_history: true # 保存历史
  fqdn: blog.annwayart.com # 自定义域名，使用 username.github.io 可删除
  on:
    branch: master # hexo 站点源文件所在的 branch
  local_dir: public 
  target_branch: gh-pages # 存放生成站点文件的 branch，使用 username.github.io 必须是 master

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - hkuliwei@126.com
  on_success: change
  on_failure: always